/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManutencoesRouteImport } from './routes/manutencoes'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResponsaveisRouteImport } from './routes/responsaveis'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PatrimoniosIndexRouteImport } from './routes/patrimonios/index'
import { Route as PatrimoniosNovoRouteImport } from './routes/patrimonios/novo'
import { Route as PatrimoniosIdIndexRouteImport } from './routes/patrimonios/$id/index'
import { Route as PatrimoniosIdEditarRouteImport } from './routes/patrimonios/$id/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencoesRoute = ManutencoesRouteImport.update({
  id: '/manutencoes',
  path: '/manutencoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsaveisRoute = ResponsaveisRouteImport.update({
  id: '/responsaveis',
  path: '/responsaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimoniosIndexRoute = PatrimoniosIndexRouteImport.update({
  id: '/patrimonios/',
  path: '/patrimonios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimoniosNovoRoute = PatrimoniosNovoRouteImport.update({
  id: '/patrimonios/novo',
  path: '/patrimonios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimoniosIdIndexRoute = PatrimoniosIdIndexRouteImport.update({
  id: '/patrimonios/$id/',
  path: '/patrimonios/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimoniosIdEditarRoute = PatrimoniosIdEditarRouteImport.update({
  id: '/patrimonios/$id/editar',
  path: '/patrimonios/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garantias': typeof GarantiasRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/setores': typeof SetoresRoute
  '/signup': typeof SignupRoute
  '/patrimonios/novo': typeof PatrimoniosNovoRoute
  '/patrimonios/': typeof PatrimoniosIndexRoute
  '/patrimonios/$id/editar': typeof PatrimoniosIdEditarRoute
  '/patrimonios/$id/': typeof PatrimoniosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garantias': typeof GarantiasRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/setores': typeof SetoresRoute
  '/signup': typeof SignupRoute
  '/patrimonios/novo': typeof PatrimoniosNovoRoute
  '/patrimonios': typeof PatrimoniosIndexRoute
  '/patrimonios/$id/editar': typeof PatrimoniosIdEditarRoute
  '/patrimonios/$id': typeof PatrimoniosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garantias': typeof GarantiasRoute
  '/historico': typeof HistoricoRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/manutencoes': typeof ManutencoesRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/perfil': typeof PerfilRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/setores': typeof SetoresRoute
  '/signup': typeof SignupRoute
  '/patrimonios/novo': typeof PatrimoniosNovoRoute
  '/patrimonios/': typeof PatrimoniosIndexRoute
  '/patrimonios/$id/editar': typeof PatrimoniosIdEditarRoute
  '/patrimonios/$id/': typeof PatrimoniosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/forgot-password'
    | '/garantias'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/manutencoes'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reset-password'
    | '/responsaveis'
    | '/setores'
    | '/signup'
    | '/patrimonios/novo'
    | '/patrimonios/'
    | '/patrimonios/$id/editar'
    | '/patrimonios/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/forgot-password'
    | '/garantias'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/manutencoes'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reset-password'
    | '/responsaveis'
    | '/setores'
    | '/signup'
    | '/patrimonios/novo'
    | '/patrimonios'
    | '/patrimonios/$id/editar'
    | '/patrimonios/$id'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/forgot-password'
    | '/garantias'
    | '/historico'
    | '/inventario'
    | '/login'
    | '/manutencoes'
    | '/movimentacoes'
    | '/perfil'
    | '/relatorios'
    | '/reset-password'
    | '/responsaveis'
    | '/setores'
    | '/signup'
    | '/patrimonios/novo'
    | '/patrimonios/'
    | '/patrimonios/$id/editar'
    | '/patrimonios/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GarantiasRoute: typeof GarantiasRoute
  HistoricoRoute: typeof HistoricoRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  ManutencoesRoute: typeof ManutencoesRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  PerfilRoute: typeof PerfilRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponsaveisRoute: typeof ResponsaveisRoute
  SetoresRoute: typeof SetoresRoute
  SignupRoute: typeof SignupRoute
  PatrimoniosNovoRoute: typeof PatrimoniosNovoRoute
  PatrimoniosIndexRoute: typeof PatrimoniosIndexRoute
  PatrimoniosIdEditarRoute: typeof PatrimoniosIdEditarRoute
  PatrimoniosIdIndexRoute: typeof PatrimoniosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencoes': {
      id: '/manutencoes'
      path: '/manutencoes'
      fullPath: '/manutencoes'
      preLoaderRoute: typeof ManutencoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsaveis': {
      id: '/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof ResponsaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonios/': {
      id: '/patrimonios/'
      path: '/patrimonios'
      fullPath: '/patrimonios/'
      preLoaderRoute: typeof PatrimoniosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonios/novo': {
      id: '/patrimonios/novo'
      path: '/patrimonios/novo'
      fullPath: '/patrimonios/novo'
      preLoaderRoute: typeof PatrimoniosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonios/$id/': {
      id: '/patrimonios/$id/'
      path: '/patrimonios/$id'
      fullPath: '/patrimonios/$id/'
      preLoaderRoute: typeof PatrimoniosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonios/$id/editar': {
      id: '/patrimonios/$id/editar'
      path: '/patrimonios/$id/editar'
      fullPath: '/patrimonios/$id/editar'
      preLoaderRoute: typeof PatrimoniosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GarantiasRoute: GarantiasRoute,
  HistoricoRoute: HistoricoRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  ManutencoesRoute: ManutencoesRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  PerfilRoute: PerfilRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponsaveisRoute: ResponsaveisRoute,
  SetoresRoute: SetoresRoute,
  SignupRoute: SignupRoute,
  PatrimoniosNovoRoute: PatrimoniosNovoRoute,
  PatrimoniosIndexRoute: PatrimoniosIndexRoute,
  PatrimoniosIdEditarRoute: PatrimoniosIdEditarRoute,
  PatrimoniosIdIndexRoute: PatrimoniosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
